FROM ubuntu 
MAINTAINER qw4wer "qw5wer@gmail.com"
ARG jdk_version=8u73
ARG jdk_b=02 

run cd /opt && mkdir /opt/java && pwd

run cd /opt && p=`ls`
#env dd $p
#run export dd=$(ls) | grep

run cd /opt/ && cd /opt/`ls` && env JAVA_HOME=`pwd` 

ARG dd=`ls`

run echo $dd

#env JAVA_HOME /opt/"$dd"

#run env

#run echo $p







