services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false  # 若通过 HTTP 访问需要设置
      - N8N_DEFAULT_LOCALE=zh-CN # 设置界面语言为中文（可选）
      - N8N_SECURE_COOKIE=false
      - TZ=Asia/Shanghai
    volumes:
      - /data/docker-data/casaos/n8n:/home/node/.n8n

