version: '2'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  proxy_pool:
    image: jhao104/proxy_pool:latest
    ports:
      - "5010:5010"
    environment:
      DB_CONN: "redis://@redis:6379/0"

