version: "3.8"
services:
  app:
    image: iceblacktea/redroid-arm64:12.0.0-240328
    container_name: gapps-game
    privileged: true
    volumes:
      - /data/docker-data/gapps-game:/data
    ports:
      - "5567:5555"
    command:
      - androidboot.redroid_gpu_mode=mali
      - androidboot.redroid_virtual_wifi=0

    devices:
      - /dev/mali0:/dev/mali0
    tty: true
    stdin_open: true