version: "3.8"
services:
  app:
    image: iceblacktea/redroid-arm64:12.0.0-240328
    container_name: local-game
    privileged: true
    volumes:
      - /data/docker-data/local-game:/data
      - /dev/mali0:/dev/mali0
    ports:
      - "5566:5555"
    command:
      - androidboot.redroid_gpu_mode=mali
      - androidboot.redroid_virtual_wifi=0
      - androidboot.redroid_net_dns1=192.168.0.225
      - androidboot.redroid_net_ndns=1
    tty: true
    stdin_open: true