name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd golang-mipsle-build-environment && docker build . --file Dockerfile --tag golang-mipsle-build-environment:$(date +%s)
